#!/bin/bash

configure_bootloader() {
    local gpu_args="$1"
    local memory_args="$2"
    
    log_header "Configuring bootloader (Limine)..."
    
    local KERNEL_ARGS="$gpu_args $memory_args"
    local MKINIT_MODULES=""

    # Build Mkinitcpio Modules
    if [ $IS_VIRT -eq 0 ]; then
        [ "$HAS_INTEL_GPU" = true ] && MKINIT_MODULES="$MKINIT_MODULES i915"
        [ "$HAS_AMD_GPU" = true ] && MKINIT_MODULES="$MKINIT_MODULES amdgpu"
        [ "$HAS_NVIDIA_GPU" = true ] && MKINIT_MODULES="$MKINIT_MODULES nvidia nvidia_modeset nvidia_uvm nvidia_drm"
    fi

    # Inject into Limine
    local start_marker="### OMARCHY-OPTIMIZER-START ###"
    local end_marker="### OMARCHY-OPTIMIZER-END ###"
    
    if [ -f "$LIMINE_CONF" ]; then
        create_backup "$LIMINE_CONF"
        sed -i "/$start_marker/,/$end_marker/d" "$LIMINE_CONF"
        cat <<EOF >> "$LIMINE_CONF"

$start_marker
# Auto-generated by Omarchy Optimizer.
KERNEL_CMDLINE[default]+="$KERNEL_ARGS"
$end_marker
EOF
        log_info "Injected kernel args into $LIMINE_CONF."
    else
        log_error "$LIMINE_CONF not found."
    fi

    # Inject into Mkinitcpio
    if [ -f "$MKINIT_CONF" ]; then
        create_backup "$MKINIT_CONF"
        sed -i -e 's/z3fold//g' -e 's/lz4_compress//g' -e 's/lz4//g' "$MKINIT_CONF"
        sed -i 's/  / /g' "$MKINIT_CONF"
        for mod in $MKINIT_MODULES; do
            if ! grep -q "$mod" "$MKINIT_CONF"; then
                sed -i "s/MODULES=(/MODULES=($mod /" "$MKINIT_CONF"
            fi
        done
        log_info "Updated modules in $MKINIT_CONF."
    fi
}

build_images() {
    log_header "Regenerating system images..."
    pacman -S --noconfirm linux > /dev/null 2>&1

    if limine-mkinitcpio; then
        log_success ":: Build successful."
    else
        log_error "Build failed. Check logs."
        exit 1
    fi

    systemctl daemon-reload
    log_warn ":: System reboot required."
}