#!/bin/bash

create_backup() {
    local target="$1"
    local backup_file="${target}.omarchy-optimizer.bkp"
    local timestamp=$(date "+%Y-%m-%d %H:%M:%S")

    if [ -f "$target" ]; then
        log_header "Backing up $(basename "$target")..."
        {
            echo ""
            echo "################################################################"
            echo "# BACKUP TIMESTAMP: $timestamp"
            echo "################################################################"
            cat "$target"
        } >> "$backup_file"
    fi
}

install_packages() {
    local pkgs="$1"
    log_header "Resolving dependencies..."
    log_info_tab_spaced "Installing: $pkgs"
    pacman -S --noconfirm --needed $pkgs > /dev/null 2>&1
}

# Usage: inject_param "key" "value" "file"
# Example: inject_param "zswap.compressor" "lz4" "/etc/default/limine"
inject_param() {
    local key="$1"
    local value="$2"
    local file="$3"

    if grep -q "$key=" "$file"; then
        # Replace key=anything with key=value
        # We use strict regex to avoid partial matches
        sed -i "s|$key=[^ \"']*|$key=$value|g" "$file"
        log_info_tab_spaced "Updated: $key -> $value"
    else
        # Add to a global buffer variable
        MISSING_FLAGS+="$key=$value "
        log_info_tab_spaced "Queued: $key=$value"
    fi
}

configure_limine() {
    local raw_args="$1"

    MISSING_FLAGS=""

    log_header "Configuring bootloader (Limine)..."
    
    if [ -f "$LIMINE_CONF" ]; then
        create_backup "$LIMINE_CONF"
        

        for arg in $raw_args; do
            local key="${arg%%=*}"
            local val="${arg#*=}"

            inject_param "$key" "$val" "$LIMINE_CONF"
        done

        if [ -n "$MISSING_FLAGS" ]; then
            local start_marker="### OMARCHY-OPTIMIZER-START ###"
            local end_marker="### OMARCHY-OPTIMIZER-END ###"
            
            # Clean old block
            sed -i "/$start_marker/,/$end_marker/d" "$LIMINE_CONF"
            
            # Append new block
            cat <<EOF >> "$LIMINE_CONF"

$start_marker
# Auto-generated by Omarchy Optimizer.
KERNEL_CMDLINE[default]+="$MISSING_FLAGS"
$end_marker
EOF
            log_info_tab_spaced "Appended missing flags."
        else
            log_info_tab_spaced "All flags updated in-place. No append needed."
        fi
        
    else
        log_error "$LIMINE_CONF not found."
    fi
}

configure_mkinitcpio() {
    local modules="$1"
    log_header "Updating mkinitcpio.conf..."
    
    if [ -f "$MKINIT_CONF" ]; then
        create_backup "$MKINIT_CONF"
        sed -i -e 's/z3fold//g' -e 's/lz4_compress//g' -e 's/lz4//g' "$MKINIT_CONF"
        sed -i 's/  / /g' "$MKINIT_CONF"
        for mod in $modules; do
            if ! grep -q "$mod" "$MKINIT_CONF"; then
                sed -i "s/MODULES=(/MODULES=($mod /" "$MKINIT_CONF"
            fi
        done
    fi
}

finalize_system() {
    log_header "Regenerating system images..."
    pacman -S --noconfirm linux > /dev/null 2>&1
    sed -i 's/#governor=.*/governor="performance"/' /etc/default/cpupower 2>/dev/null
    sed -i 's/governor=.*/governor="performance"/' /etc/default/cpupower 2>/dev/null
    systemctl enable --now cpupower.service > /dev/null 2>&1

    if limine-mkinitcpio; then
        log_success ":: Optimization successful."
    else
        log_error "Build failed. Check logs."
        exit 1
    fi

    systemctl daemon-reload
    log_warn ":: System reboot required."
}