#!/bin/bash

configure_storage() {
    log_header "Configuring storage I/O schedulers..."

    local udev_dir=$(dirname "$UDEV_IO_RULES")

    if [ ! -d "$udev_dir" ]; then
        mkdir -p "$udev_dir"
    fi

    if [ -f "$UDEV_IO_RULES" ]; then
        create_backup "$UDEV_IO_RULES"
    fi

    cat <<EOF > "$UDEV_IO_RULES"
# Auto-generated by Omarchy Optimizer.
# Sets I/O scheduler based on device type.

# NVMe drives -> none
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="none"

# SSDs and eMMC (Non-rotational) -> mq-deadline
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"

# HDDs (Rotational) -> bfq
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
EOF

    log_info "Created udev rules at $UDEV_IO_RULES"

    if udevadm control --reload && udevadm trigger; then
        log_success "Applied I/O schedulers."
    else
        log_warn "Could not reload udev. Reboot required to apply changes."
    fi
}
